version: '3'
services:
   node:
      image: "msg-api-node-mdb:latest"
      user: "node"
      working_dir: /home/node/utl-api-node-mdb
      environment:
        - NODE_ENV=production
        - DB_HOST=mongodb-webnet
      ports:
        - 1337:1337
      expose:
        - "1337"
#      command: "\"npm test\""
      networks:
        - webnet
      depends_on:
        - mongo
   mongo:
      image: "mongo:3.4.20"
      container_name: "mongodb-webnet"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/logs
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27107
      networks:
        - webnet
networks:
  webnet:

