version: '3'
services:
   node:
      image: "utl-api-node-mdb:latest"
      user: "node"
      working_dir: /home/node/utl-api-node-mdb
      environment:
        - NODE_ENV=production
        - DB_HOST=mongodb
      volumes:
        - ./:/home/node/utl-api-node-mdb
      ports:
        - 3000:3000
      expose:
        - "3000"
      command: "npm start"
      networks:
        - webnet
   mongo:
      image: "mongo:3.4.20"
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/logs
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27107
      networks:
        - webnet
networks:
  webnet:

