pipeline {
	agent {
		docker {
			image 'node:7-alpine'

		}
	}
	stages {
		stage ('Build' ) {
			steps {
			def customImage = docker.build ("msg-api-node-mdb:latest")
			}
		}
		stage ('Test' ) {
			steps {
				sh 'node --version'
			}
		}
	}
}

